In [2]:
import pandas as pd


data = {
    "Customer_ID": [101, 102, 103, 104, 105, 102, 106],
    "Name": ["Aisha", "Rahul", "Priya", "Kumar", "Sara", "Rahul", "Arun"],
    "Email": [
        "aisha@gmail.com",
        "rahul@gmail.com",
        "priya@gmail.com",
        "kumar@gmail.com",
        "sara@gmail.com",
        "rahul@gmail.com",
        "arun@gmail.com"
    ]
}

df = pd.DataFrame(data)


df.to_csv("customer_data.csv", index=False)


df

   Customer_ID   Name            Email
0          101  Aisha  aisha@gmail.com
1          102  Rahul  rahul@gmail.com
2          103  Priya  priya@gmail.com
3          104  Kumar  kumar@gmail.com
4          105   Sara   sara@gmail.com
5          102  Rahul  rahul@gmail.com
6          106   Arun   arun@gmail.com

In [3]:


duplicates = df[df.duplicated(keep=False)]

print("Duplicate Records:")
duplicates

Duplicate Records:

   Customer_ID   Name            Email
1          102  Rahul  rahul@gmail.com
5          102  Rahul  rahul@gmail.com

In [4]:


df_cleaned = df.drop_duplicates()

print("Original number of records:", len(df))
print("Records after removing duplicates:", len(df_cleaned))

df_cleaned

Original number of records: 7
Records after removing duplicates: 6

   Customer_ID   Name            Email
0          101  Aisha  aisha@gmail.com
1          102  Rahul  rahul@gmail.com
2          103  Priya  priya@gmail.com
3          104  Kumar  kumar@gmail.com
4          105   Sara   sara@gmail.com
6          106   Arun   arun@gmail.com

In [5]:


new_customer = {
    "Customer_ID": 107,
    "Name": "Meena",
    "Email": "meena@gmail.com"
}


if (new_customer["Customer_ID"] in df_cleaned["Customer_ID"].values or
    new_customer["Email"] in df_cleaned["Email"].values):

    print("Duplicate data found! Customer cannot be added.")

else:
    df_cleaned = pd.concat(
        [df_cleaned, pd.DataFrame([new_customer])],
        ignore_index=True
    )
    print("New customer is unique and has been added.")

df_cleaned

New customer is unique and has been added.

   Customer_ID   Name            Email
0          101  Aisha  aisha@gmail.com
1          102  Rahul  rahul@gmail.com
2          103  Priya  priya@gmail.com
3          104  Kumar  kumar@gmail.com
4          105   Sara   sara@gmail.com
5          106   Arun   arun@gmail.com
6          107  Meena  meena@gmail.com

In [6]:


df_cleaned.to_csv("final_customer_data.csv", index=False)

print("Final customer data saved successfully!")

Final customer data saved successfully!

In [7]:


print("Total records:", len(df_cleaned))
print("Duplicate records:", df_cleaned.duplicated().sum())
print("\nFinal Dataset:")
display(df_cleaned)

Total records: 7
Duplicate records: 0

Final Dataset:

   Customer_ID   Name            Email
0          101  Aisha  aisha@gmail.com
1          102  Rahul  rahul@gmail.com
2          103  Priya  priya@gmail.com
3          104  Kumar  kumar@gmail.com
4          105   Sara   sara@gmail.com
5          106   Arun   arun@gmail.com
6          107  Meena  meena@gmail.com